---
title: "Portfolio"
author: "Mia Murphy"
date: "2023-10-06"
output: rmdformats::downcute
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
**Location:** Quechee, Vermont  
**Email:** [miamurphyvt@gmail.com](mailto:miamurphyvt@gmail.com)  

## Welcome to My Data Analytics Portfolio!

Hello, I’m Mia Murphy—a dynamic full-stack Data Analyst and seasoned Digital Marketing Specialist with over 22 years of experience in graphic design and web consultancy. My academic journey began at the University of Vermont, where I earned a degree in Economics and Statistics, setting the foundation for my data-driven career. I am currently advancing my expertise through a Master's in Data Science, specializing in sophisticated data analysis and visualization techniques.

This portfolio is a meticulously curated showcase of my work, demonstrating my prowess in translating complex data into strategic insights. My projects span sustainable fashion analytics to e-commerce optimization, each reflecting my journey and growth in the field. Armed with advanced skills in R, Python, Tableau, SAS, and full-stack web technologies, I offer a comprehensive toolkit to drive data intelligence and enhance marketing strategies.

With my extensive background as a Graphic Artist and Web Designer, I bring a unique perspective to digital marketing and data analytics. My ability to integrate visual design with data science allows me to uncover and leverage insights that traditional analytics might overlook. I will find valuable insights and trends that automated third-party software will miss.

I will evaluate webpages for best SEO practices, including competitor analysis to match SEO trends in target industries, including ad campaign management to ensure ad campaigns are generating the best conversion rates and returns on investment. I will also automate time-consuming, repetitive tasks so that I may focus on productivity. This fusion of skills empowers businesses to capture nuanced market trends and engage customers more effectively.

As I continue to refine my portfolio using CSS, HTML, and JavaScript, I invite you to preview my ongoing projects here. My goal is to deliver actionable insights and robust data-driven strategies that propel your business forward.

Thank you for visiting. I am eager to explore potential collaborations and connect with other data and marketing professionals. Let's harness the power of data and creativity to uncover new opportunities together!

I am also working on a portfolio page with CSS, HTML and JavaScript. It will replace this current portfolio when complete.

Get a preview of it here: [**Portfolio in progress**](https://nightskyfirefly.github.io/portfolio/index/index.html)


## Certifications

- [**Google Data Analytics Certification**](https://coursera.org/share/a2f186954990e25e6aca88c97c518dde)

- UVM Digital Marketing Certification

- UVM Data Analytics for Business Certification

## Resume

- [**Resume link**](https://nightskyfirefly.github.io/portfolio/resume.html)

## Projects

These projects are a product of self-direction and independent exploration, showcasing my ability to identify interesting and relevant questions, gather and clean the necessary data, conduct comprehensive analyses, and communicate the findings effectively. Each project is accompanied by a full set of data analysis code as well as detailed summary reports tailored for stakeholders. The initiative taken in these projects demonstrates my proactive approach and my capability to drive investigations from start to finish, delivering actionable insights and valuable knowledge.


### Large Projects

Here is my latest project, which involved writing several intricate Python scripts to scrape data from the web and generate a dataset for my personal use.

- [**Fragrance Exploratory Data Analysis**](https://nightskyfirefly.github.io/portfolio/projects/Fragrance_Analysis_1.html)



### Archived Projects

These will eventually be removed from the main portfolio but still accessable through an archive link.

#### Python
- [**Rural Business Marketing Strategy**](https://nightskyfirefly.github.io/portfolio/vermont/RuralBusiness.html)
- [**Vermont Disaster Preparation**](https://nightskyfirefly.github.io/portfolio/vermont/Vermont_Disaster.html)
- [**Real Estate data set analysis using Python**](https://nightskyfirefly.github.io/portfolio/projects/MiaRealEstatePython.html)
- [**Real Estate data set data visualization using Bokeh in Python**](https://nightskyfirefly.github.io/portfolio/projects/MiaPythonBokeh.html)

#### R

- [**Real Estate data analysis using R. Pt. 1**](https://nightskyfirefly.github.io/portfolio/projects/Mia_Real_Estate_Analysis.html)
- [**Real Estate data analysis using R. Pt. 2**](https://nightskyfirefly.github.io/portfolio/projects/Mia_Oldtown.html)
- [**Real Estate data analysis using R. Pt. 3**](https://nightskyfirefly.github.io/portfolio/projects/Mia_Oldtown_Summary.html)

#### SQL

- [**Creating a data set in SQL and performing a full data analysis**](https://nightskyfirefly.github.io/portfolio/projects/MiaSQLCoffee.html)
- [**Writing a summary report for the above data analysis**](https://nightskyfirefly.github.io/portfolio/projects/MiaCoffeeSummary.html)